### ISSUE TITLE
Replace spinners-react with a different library

### ISSUE THREAD

**Issue by VikSil** [VikSil/howtoquant-frontend#1]
`Loading` component uses `spinners-react` library which is causing runtime warnings:

`Warning: Wrapper: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

Should be replaced with a different spinner library and styled according to the look-and-feel of the website.

**Comment by aadarsh10c** [comment]
Hey @VikSil , is this issue still opened ?

**Comment by VikSil** [comment]
Hi @aadarsh10c. Yes, still open, you can have a go at it, if you want to.

**Comment by aadarsh10c** [comment]
@VikSil  ,Sure please assign me

**Comment by aadarsh10c** [comment]
@VikSil , are u open to a pure CSS loader ? 

https://codepen.io/adarsh-kumar-the-decoder/pen/WNVrrzr

**Comment by VikSil** [comment]
@aadarsh10c CSS loader is acceptable, as long as it has the correct background color and is integrated into the `Loading` component.

**Comment by aadarsh10c** [comment]
@VikSil , pls check
